# This is an example Hyprland config file. TODO
# Refer to the wiki for more information.
# https://wiki.hypr.land/Configuring/

# Please note not all available settings / options are set here.
# For a full list, see the wiki

# You can split this configuration into multiple files
# Create your files separately and then link them to this file like this:
# source = ~/.config/hypr/myColors.conf

source = ~/.config/hypr/core/animations.conf
source = ~/.config/hypr/core/autostart.conf
source = ~/.config/hypr/core/binds.conf
source = ~/.config/hypr/core/defaults.conf
source = ~/.config/hypr/core/env.conf
source = ~/.config/hypr/core/input.conf
source = ~/.config/hypr/core/looknfeel.conf
source = ~/.config/hypr/core/monitors.conf
source = ~/.config/hypr/core/permissions.conf
source = ~/.config/hypr/core/rules.conf


# See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
dwindle {
    preserve_split = true # You probably want this
}

# See https://wiki.hypr.land/Configuring/Master-Layout/ for more
master {
    new_status = master
}

# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    force_default_wallpaper = 1 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
}
