# Default Programs

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = ghostty
$fileManager = nemo
$menu = vicinae toggle
# $menu = pgrep wofi >/dev/null 2>&1 && killall wofi || wofi --conf ~/.config/wofi/config --style ~/.config/wofi/style.css --show drun

