
# See https://wiki.hypr.land/Configuring/Monitors/
# Integrated display
monitor=eDP-1,preferred,auto,1.33333

# 4K monitor in the basement 
monitor=desc:Samsung Electric Company U32E850 HTHGC00006, preferred, auto, 1.3333

# Ultrawide monitor at UBreakiFix Sandy
monitor=desc:ASUSTek COMPUTER INC ASUS VP299CL MBLMTF132339, preferred, auto-center-up, auto
